// src/components/ui/EmptyState.vue
<script setup lang="ts">
interface Props {
  title: string
  description?: string
}

defineProps<Props>()
</script>

<template>
  <div
    style="
      text-align: center;
      padding: 48px 24px;
      background-color: #f9fafb;
      border-radius: 12px;
      border: 2px dashed #e5e7eb;
    "
  >
    <div style="margin-bottom: 12px; color: #9ca3af">
      <slot name="icon" />
    </div>
    <p
      style="
        color: #6b7280;
        margin: 0;
        font-size: 0.95rem;
        font-weight: 500;
      "
    >
      {{ title }}
    </p>
    <p
      v-if="description"
      style="color: #9ca3af; margin: 4px 0 0 0; font-size: 0.85rem"
    >
      {{ description }}
    </p>
    <div v-if="$slots.action" style="margin-top: 16px">
      <slot name="action" />
    </div>
  </div>
</template>

// src/components/ui/EmptyState.tsx
import React from 'react';

export interface EmptyStateProps {
    icon: React.ReactNode;
    title: string;
    description?: string;
    action?: React.ReactNode;
}

export const EmptyState: React.FC<EmptyStateProps> = ({ icon, title, description, action }) => {
    return (
        <div style={{
            textAlign: 'center', padding: '48px 24px',
            backgroundColor: '#f9fafb', borderRadius: '12px',
            border: '2px dashed #e5e7eb',
        }}>
            <div style={{ marginBottom: '12px', color: '#9ca3af' }}>{icon}</div>
            <p style={{ color: '#6b7280', margin: 0, fontSize: '0.95rem', fontWeight: '500' }}>{title}</p>
            {description && <p style={{ color: '#9ca3af', margin: '4px 0 0 0', fontSize: '0.85rem' }}>{description}</p>}
            {action && <div style={{ marginTop: '16px' }}>{action}</div>}
        </div>
    );
};
