// src/components/ui/Spinner.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ArrowPathIcon } from '@heroicons/vue/24/outline'

export type SpinnerSize = 'sm' | 'md' | 'lg'

interface Props {
  size?: SpinnerSize
  color?: string
  text?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
  color: '#3b82f6',
})

const sizeMap: Record<SpinnerSize, number> = { sm: 20, md: 32, lg: 48 }
const px = computed(() => `${sizeMap[props.size]}px`)
</script>

<template>
  <div
    style="
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 12px;
    "
  >
    <ArrowPathIcon
      :style="{
        width: px,
        height: px,
        color: color,
        animation: 'spin 1s linear infinite',
      }"
    />
    <span v-if="text" style="color: #6b7280; font-size: 0.9rem">{{ text }}</span>
  </div>
</template>

// src/components/ui/Spinner.tsx
import React from 'react';
import { ArrowPathIcon } from '@heroicons/react/24/outline';

export interface SpinnerProps {
    size?: 'sm' | 'md' | 'lg';
    color?: string;
    text?: string;
}

const sizeMap = { sm: 20, md: 32, lg: 48 };

export const Spinner: React.FC<SpinnerProps> = ({
                                                    size = 'md',
                                                    color = '#3b82f6',
                                                    text,
                                                }) => {
    return (
        <div style={{
            display: 'flex', flexDirection: 'column',
            alignItems: 'center', justifyContent: 'center', gap: '12px'
        }}>
            <ArrowPathIcon style={{
                width: sizeMap[size], height: sizeMap[size], color,
                animation: 'spin 1s linear infinite',
            }} />
            {text && <span style={{ color: '#6b7280', fontSize: '0.9rem' }}>{text}</span>}
            <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
        </div>
    );
};
